# Generated by Django 5.0 on 2023-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('reservation', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('exam_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('questions', models.JSONField()),
            ],
        ),
    ]
