# Generated by Django 5.0 on 2023-12-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_type', models.CharField(max_length=20)),
                ('points', models.FloatField()),
                ('image_path', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='prova',
            options={'ordering': ['id', 'reservation']},
        ),
        migrations.AlterUniqueTogether(
            name='prova',
            unique_together={('id', 'reservation')},
        ),
    ]
