app:
  listen: ":3000"
  # head /dev/urandom | tr -dc A-Za-z0-0 | openssl dgst -sha256
  jwt-secret: "10152ac15c5c8ac4bc48cb1dea05b0274e0f64577e6c760ed1f4d0e7730e0ad2"

endpoints:
  users:
    base:
      "localhost:3000/v1/users"

    get:
      uri: "/user"
      method: "GET"
