version: '3'
services:
  interface:
    container_name: interfac
    build: ./interface
    ports:
      - 8000:8000
    networks:
      - projectnet

  api:
    container_name: ap
    build: ./api
    ports:
      - 8001:8001
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/Project
    networks:
      - projectnet

  auth:
    container_name: aut
    build: ./auth
    ports:
      - 8002:8002
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/Project
    networks:
      - projectnet

  mongodb:
    container_name: project-mongodb
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data/inquiricoes.json:/data/db/inquiricoes.json
      - ./data/users.json:/data/db/users.json
      - ./data/posts.json:/data/db/posts.json
      - ./data/sugestoes.json:/data/db/sugestoes.json
    
    networks:
      - projectnet

networks:
  projectnet:
    name: projectnet
    driver: bridge
volumes:
  projectData:
